name: Update OpenRouter Models

on:
  schedule:
    - cron: "0 6 * * 1" # Mondays at 06:00 UTC
  workflow_dispatch:

jobs:
  refresh-models:
    runs-on: ubuntu-latest
    env:
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      OPENROUTER_SITE_URL: ${{ secrets.OPENROUTER_SITE_URL }}
      OPENROUTER_TITLE: ${{ secrets.OPENROUTER_TITLE }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Update OpenRouter models
        run: npm run openrouter:models

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if git diff --stat --exit-code; then
            echo "No changes to commit"
          else
            git add docs/openrouter/models.json docs/openrouter/models-summary.md
            git commit -m "chore: refresh OpenRouter models"
            git push
          fi
